### ISSUE TITLE
PNG Transparency ?

### ISSUE THREAD

**Issue by Karl4RediDoc** [kbwood/signature#13]
How can I save a png with transparency ?
I can not find anything explaining how.

Regards,
~ KS

**Comment by kbwood** [comment]
In the Java code you can replace the background colour (`Color.WHITE`) with transparency (`new Color(255, 255, 255, 0)`). I don't know how you'd do it in the C# code, but I imagine it would be similar.

**Comment by Karl4RediDoc** [comment]
I am running in php.

**Comment by Karl4RediDoc** [comment]
OK, How do we set background-color ?

**Comment by Karl4RediDoc** [comment]
A signature with a white box around it, is useless.

**Comment by kbwood** [comment]
You can set the background colour with the `background` option.
