### ISSUE TITLE
Clearing with background set to transparent

### ISSUE THREAD

**Issue by SethRAH** [kbwood/signature#19]
If you call `$('#sig').signature('clear')` when your background is set to transparent black, no visual clear happens to the context but the data is gone. It looks like this is happening because its using `ctx.fillRect(...)` and filling with transparent (which doesn't actually write over anything. I think you would have a similar issue with any color that has any amount of transparency. 

I have a work around where my event handler will call `ctx.clearRect(...)` before calling the signature clear. If the background isn't purely transparent, I guess you could call the `ctx.clearRect(...)` followed by a `ctx.fillRect(...)` to reset the background.

**Comment by kbwood** [comment]
I've added this in v1.2.1.
