### ISSUE TITLE
Performance on Android

### ISSUE THREAD

**Issue by joaopiopedreira** [kbwood/signature#2]
Hi @kbwood,

I'm currently using the [jSignature](http://willowsystems.github.io/jSignature/#/about/) jQuery plugin in my cordova app. The performance on iOS is great, but on Android (even 4.4+) sucks.

Should I expect a performance gain from using your plugin (relative to jSignature)?

Thanks, Joao

**Comment by kbwood** [comment]
Sorry, I don't know. I don't have an Android device to test it on.
