### ISSUE TITLE
Signature Pad not working on Touch screens or Tablets

### ISSUE THREAD

**Issue by bevinGithub** [kbwood/signature#20]
I have used the signature plugin and works fine using the mouse. The only issue l am having is when you using a tablet or a touch screen. Its not drawing a line only dots  when you first you touch the signature area.

Any ideas will be most appreciated

**Comment by kanemcnamara** [comment]
I'm also having the same issue :(

**Comment by kbwood** [comment]
Does your tablet work on this page? http://keith-wood.name/signatureBasicsTouch.html
If so, you need to add the TouchPunch plugin to your page, as described in the Usage section half way down the plugin Web page (http://keith-wood.name/signature.html).

**Comment by kanemcnamara** [comment]
> Does your tablet work on this page? http://keith-wood.name/signatureBasicsTouch.html If so, you need to add the TouchPunch plugin to your page, as described in the Usage section half way down the plugin Web page (http://keith-wood.name/signature.html).

The issue I'm having is limited to Microsoft Surfaces as far as i can tell, everything is working fine on iPad/Android etc. The issue is also present on the link you sent.

**Comment by kbwood** [comment]
Sorry, I don't have a Microsoft Surface to test with.

**Comment by kanemcnamara** [comment]
Just jumping in here for anyone else who stumbles across the same problem; 
This fork of the TouchPunch library resolves the issue
[https://github.com/RWAP/jquery-ui-touch-punch](https://github.com/RWAP/jquery-ui-touch-punch)

**Comment by kbwood** [comment]
Thanks. I've updated the plugin page to refer to that instead of the original.
